name: Publish Packages
permissions:
  contents: write

on:
  push:
    branches:
      - next
      - release
    paths:
      - 'packages/**/*'
      - 'app/**/*'
      - 'pnpm-lock.yaml'
      - 'package.json'

env:
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: debug env
        run: |
          echo "FEISHU_WEBHOOK_URL=${FEISHU_WEBHOOK_URL}"
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}

      - name: debug env
        run: |
          echo "ACCESS_TOKEN=${ACCESS_TOKEN}"
        env:
          ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 0 indicates all history for all branches and tags，保留所有历史，为了让lerna publish 时可以生成有效的change log
          fetch-depth: '0'
          token: ${{ secrets.GITHUB_TOKEN }}

        # lerna publish 后会提交代码到master分支，这里是为了配置 git 用户，区分用户
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: SetUp node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v5.0.0
        with:
          cache: true

      - name: Creat .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}
          EOF

      - name: Install dependencies
        run: pnpm install

      - name: Build
        id: build
        run: pnpm run build

      - name: Publish next
        if: github.ref_name == 'next'
        run: pnpm run next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: github.ref_name == 'release'
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Info
        id: info
        run: |
          publish=$(git rev-parse HEAD)
          current=${{github.sha}}
          tags=$(git tag --list --contains $publish)
          if [ "$current" != "$publish" ] && [ -n "tags" ]; then
            echo "versions="$(echo "$tags" | sed 's/@1ssue/{0}@1ssue/g')"" >> $GITHUB_OUTPUT
          fi

      # ✅ 成功通知
      - name: Notify Feishu on success
        if: steps.info.outputs.versions
        run: node scripts/notify-feishu.js
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          BUILD_STATUS: success
          BUILD_REPO: ${{ github.repository }}
          BUILD_REF: ${{ github.ref_name }}
          BUILD_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # ❌ 失败通知
      - name: Notify Feishu on failure
        if: failure()
        run: node scripts/notify-feishu.js
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          BUILD_STATUS: failure
          BUILD_REPO: ${{ github.repository }}
          BUILD_REF: ${{ github.ref_name }}
          BUILD_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

#      # ❌ 失败通知
#      - name: Notify WeChat on failure
#        if: failure()
#        run: node scripts/notify-weixin.js
#        env:
#          WX_APP_ID: ${{ secrets.APP_ID }}
#          WX_APP_SECRET: ${{ secrets.APP_SECRET }}
#          WX_TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
#          WX_OPEN_ID: ${{ secrets.OPEN_ID }}
#          BUILD_STATUS: failure
#          BUILD_REPO: ${{ github.repository }}
#          BUILD_REF: ${{ github.ref_name }}
#          BUILD_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
#
#      # ✅ 成功通知
#      - name: Notify WeChat on success
#        if: steps.info.outputs.versions
#        run: node scripts/notify-weixin.js
#        env:
#          WX_APP_ID: ${{ secrets.APP_ID }}
#          WX_APP_SECRET: ${{ secrets.APP_SECRET }}
#          WX_TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
#          WX_OPEN_ID: ${{ secrets.OPEN_ID }}
#          BUILD_STATUS: success
#          BUILD_REPO: ${{ github.repository }}
#          BUILD_REF: ${{ github.ref_name }}
#          BUILD_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
